### ISSUE TITLE
Import error with extract_msg

### ISSUE THREAD

**Issue by gwiedeman** [UAlbanyArchives/mailbagit#237]
**Describe the bug**
Using later versions of extract_msg results in an import error.

**To Reproduce**
install extract_msg 0.42.0 or later
run `mailbagit -h`

```
Traceback (most recent call last):
  File "C:\Users\gw234478\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\gw234478\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\gw234478\AppData\Local\Programs\Python\Python39\Scripts\mailbagit.exe\__main__.py", line 4, in <module>
  File "C:\Users\gw234478\projects\mailbagit\mailbagit\__init__.py", line 39, in <module>
    import_formats(plugin_dirs["formats"])
  File "C:\Users\gw234478\projects\mailbagit\mailbagit\email_account.py", line 65, in import_formats
    import mailbagit.formats.msg
  File "C:\Users\gw234478\projects\mailbagit\mailbagit\formats\msg.py", line 12, in <module>
    from extract_msg import attachment
  File "C:\Users\gw234478\AppData\Local\Programs\Python\Python39\lib\site-packages\extract_msg\attachment.py", line 21, in <module>
    from .attachment_base import AttachmentBase
  File "C:\Users\gw234478\AppData\Local\Programs\Python\Python39\lib\site-packages\extract_msg\attachment_base.py", line 19, in <module>
    from .properties import Properties
ImportError: cannot import name 'Properties' from 'extract_msg.properties' (C:\Users\gw234478\AppData\Local\Programs\Python\Python39\lib\site-packages\extract_msg\properties\__init__.py)
```

**Comment by gwiedeman** [comment]
addressed with #238
