### ISSUE TITLE
Error handling issue

### ISSUE THREAD

**Issue by jtruitt1** [UAlbanyArchives/mailbagit#250]
**Describe the bug**
Errors with writing attachments aren't handled and crash the program.

**To Reproduce**
1. Run the following 
```shell
mailbagit -k 110608\ BS\ saturday.msg -m Mailbag -i msg -d pdf eml
```
I can privately share the file triggering this issue, but do not want to post it publicly.

**Expected behavior**

**Program Output**
```python
INFO: Reading: 110608 BS saturday.msg
INFO: Found 1 messages.
Traceback (most recent call last):
  File "/Users/jtruitt1/Downloads/MailBagit_testing/mailbagit/mailbagit/helper/controller.py", line 109, in writeAttachmentsToDisk
    f = open(attachment_path, "wb")
ValueError: embedded null byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jtruitt1/opt/miniconda3/bin/mailbagit", line 33, in <module>
    sys.exit(load_entry_point('mailbagit', 'console_scripts', 'mailbagit')())
  File "/Users/jtruitt1/Downloads/MailBagit_testing/mailbagit/mailbagit/__init__.py", line 251, in cli
    main(args)
  File "/Users/jtruitt1/Downloads/MailBagit_testing/mailbagit/mailbagit/__init__.py", line 313, in main
    return c.generate_mailbag()
  File "/Users/jtruitt1/Downloads/MailBagit_testing/mailbagit/mailbagit/controller.py", line 174, in generate_mailbag
    controller.writeAttachmentsToDisk(self.args.dry_run, attachments_dir, message)
  File "/Users/jtruitt1/Downloads/MailBagit_testing/mailbagit/mailbagit/helper/controller.py", line 117, in writeAttachmentsToDisk
    errors = common.handle_error(errors, None, desc, "error")
UnboundLocalError: local variable 'errors' referenced before assignment
```

**Environment (please complete the following information):**
- GUI or command line?: CLI
- OS: Mac OS 13.5
- Python version: Python 3.9.5

**Additional context**
Whatever the issue is with the `ValueError`, it seems that the exception handling is failing because `errors` isn't defined in helper/controller.py

**Comment by gwiedeman** [comment]
Thanks for catching and this @jtruitt1 ! Can you send the msg to gwiedeman [at] albany [dot] edu? I think its an easy fix but I don't have a handy example to test.
